import time
import requests
import json
import sys

API_BASE = "http://localhost:8000"

print("Starting local pipeline test...")
r = requests.post(f"{API_BASE}/api/scripts/upload", data={
    "script_text": "This is a test script using the free local setup. We test four second scenes. The audio should be generated by gTTS. Images will be requested from Unsplash. Finally the video will be rendered.",
    "voice_style": "calm"
})

if r.status_code != 200:
    print(f"Failed to upload script: {r.text}")
    sys.exit(1)

project_id = r.json()["project_id"]
print(f"Project created: {project_id}")

for idx in range(60):
    time.sleep(3)
    status_req = requests.get(f"{API_BASE}/api/pipeline/{project_id}/status")
    data = status_req.json()
    status = data.get("overall_status", "unknown")
    print(f"[{idx*3}s] Status: {status}")
    if status in ("complete", "error"):
        print(f"Final status: {status}")
        print(json.dumps(data, indent=2))
        sys.exit(0 if status == "complete" else 1)

print("Timeout waiting for pipeline to complete.")
sys.exit(1)
