"""
Metadata sanitization for the ScriptToVideo pipeline.

sanitize_metadata(raw)
    → Normalises title length, deduplicates description, cleans tags.

build_description(title, script_text, config)
    → Constructs a clean, non-duplicated YouTube description.

normalize_subtitle_text(text)
    → Normalises unicode characters for safe SRT output.
"""

import re
import logging

logger = logging.getLogger(__name__)


# ── public API ────────────────────────────────────────────────────────────────

def sanitize_metadata(raw: dict) -> dict:
    """
    Sanitize and normalise a raw metadata dict.

    Fixes:
    - Title truncated at 60 characters with ellipsis
    - Description deduplicated line-by-line
    - Tags lowercased, stripped, deduplicated, limited to 30
    - Hashtags deduplicated
    """
    title       = _sanitize_title(raw.get("title",       ""))
    description = _sanitize_description(raw.get("description", ""))
    tags        = _sanitize_tags(raw.get("tags",        []))
    hashtags    = _sanitize_hashtags(raw.get("hashtags", []))

    result = {**raw, "title": title, "description": description, "tags": tags}
    if hashtags:
        result["hashtags"] = hashtags

    logger.info(
        "sanitize_metadata: title=%d chars, desc=%d chars, %d tags",
        len(title), len(description), len(tags),
    )
    return result


def build_description(
    title: str,
    script_text: str,
    category: str = "general",
    top_tags: list[str] | None = None,
) -> str:
    """
    Build a clean, non-duplicated YouTube description.

    Structure:
    1. Hook line (distinct from title)
    2. Blank line
    3. Script excerpt (skips first sentence to avoid duplication)
    4. Blank line
    5. Structured sections
    6. Hashtags
    """
    if not top_tags:
        top_tags = []

    # Hook: use the first sentence but don't start with the title verbatim
    sentences = [s.strip() for s in re.split(r'(?<=[.!?])\s+', script_text) if s.strip()]
    hook = sentences[0] if sentences else title

    # Body: start FROM the second sentence to avoid repeating the hook
    body_sentences = sentences[1:5] if len(sentences) > 1 else []
    body = " ".join(body_sentences)
    if body and not body.endswith((".", "!", "?")):
        body += "..."

    hashtag_line = " ".join(f"#{t}" for t in top_tags[:5]) if top_tags else f"#{category}"

    parts = [
        hook,
        "",
        body,
        "",
        "📌 In this video:",
        f"• {title}",
        "",
        "🕐 TIMESTAMPS:",
        "0:00 – Introduction",
        "",
        "Generated by ScriptToVideo AI Pipeline.",
        hashtag_line,
    ]
    # Filter consecutive blank lines
    cleaned: list[str] = []
    prev_blank = False
    for line in parts:
        is_blank = not line.strip()
        if is_blank and prev_blank:
            continue
        cleaned.append(line)
        prev_blank = is_blank

    return "\n".join(cleaned).strip()


def normalize_subtitle_text(text: str) -> str:
    """
    Normalize unicode characters in subtitle text for safe SRT output.

    Fixes:
    - Curly/smart apostrophes → straight apostrophe
    - Curly/smart quotes → straight double-quote
    - Em dash / en dash → hyphen with spaces
    - Null bytes removed
    - Whitespace normalized
    """
    # Apostrophes
    text = text.replace("\u2018", "'").replace("\u2019", "'")  # ' '
    text = text.replace("\u02bc", "'")                          # modifier apostrophe

    # Quotation marks
    text = text.replace("\u201c", '"').replace("\u201d", '"')   # " "
    text = text.replace("\u00ab", '"').replace("\u00bb", '"')   # « »
    text = text.replace("\u2039", "'").replace("\u203a", "'")   # ‹ ›

    # Dashes
    text = text.replace("\u2014", " - ")   # em dash
    text = text.replace("\u2013", " - ")   # en dash
    text = text.replace("\u2012", " - ")   # figure dash

    # Ellipsis
    text = text.replace("\u2026", "...")   # …

    # Control characters + null bytes
    text = re.sub(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]", "", text)

    # Normalize whitespace
    text = " ".join(text.split())

    return text.strip()


# ── private helpers ───────────────────────────────────────────────────────────

def _sanitize_title(title: str) -> str:
    title = " ".join(title.split())   # collapse internal whitespace
    title = title.strip()
    if len(title) > 60:
        # Trim at word boundary
        trimmed = title[:57].rsplit(" ", 1)[0]
        title = trimmed.rstrip(",.;:") + "..."
    return title


def _sanitize_description(desc: str) -> str:
    """Deduplicate lines, collapse excess blank lines."""
    lines = desc.split("\n")
    seen: set[str] = set()
    cleaned: list[str] = []
    prev_blank = False

    for line in lines:
        norm = line.strip()
        is_blank = not norm

        if is_blank:
            if not prev_blank:        # allow at most one consecutive blank
                cleaned.append("")
            prev_blank = True
            continue

        if norm in seen:              # skip exact-duplicate non-blank lines
            prev_blank = False
            continue

        seen.add(norm)
        cleaned.append(line.rstrip())
        prev_blank = False

    return "\n".join(cleaned).strip()


def _sanitize_tags(tags: list) -> list[str]:
    """Lowercase, strip, deduplicate, limit to 30."""
    if not isinstance(tags, list):
        return []
    seen: dict[str, None] = {}
    for t in tags:
        clean = str(t).lower().strip().replace("#", "")
        if clean and clean not in seen:
            seen[clean] = None
    return list(seen.keys())[:30]


def _sanitize_hashtags(hashtags: list) -> list[str]:
    if not isinstance(hashtags, list):
        return []
    seen: dict[str, None] = {}
    for h in hashtags:
        clean = str(h).strip()
        if not clean.startswith("#"):
            clean = "#" + clean
        if clean not in seen:
            seen[clean] = None
    return list(seen.keys())[:10]
